name: Deploy to EC2

on:
  push:
    branches:
      - main # Adjust branch as needed


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.60.181.19 << EOF
        cd Site
        git pull origin main
        rm -rf /var/www/html/*
        cp -r /home/ubuntu/Site/* /var/www/html/
        sudo systemctl restart nginx # Restart web server
