name: Deploy to EC2

on:
  push:
    branches:
      - main # Adjust branch as needed


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "$PRIVATE_KEY" > github-ec2.pem && chmod 600 github-ec2.pem
        ssh -o StrictHostKeyChecking=no -i github-ec2.pem  ubuntu@13.60.181.19

        ssh-keygen -t ed25519 -C "your-email@example.com"
        cat ~/.ssh/id_ed25519.pub


        cd
        cd /var/www
        sudo chown -R $USER:$USER /var/www
        git clone git@github.com:jhygate/Site.git
        ls
        cd /var/www/Site
        git pull origin main
        rm -rf /var/www/html/*
        cp -r /var/www/Site/* /var/www/html/
        sudo systemctl restart nginx # Restart web server
